name: build
on: 
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: curl http://cloud.simonsson.international/.well-known/acme-challenge/var_www_letsencrypt              
