name: Test rust code

on:
  push:
    branches:
      - master
  pull_request:

env:
  nightly: nightly-2022-09-20
  target: wasm32-unknown-unknown
  tarpaulin-vers: "0.20.0"
  try-runtime-chain: dev
  try-runtime-uri: wss://eden-rpc.dwellir.com:443

jobs:
  try-runtime:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - name: Check Version
        run: |
         echo -n "edenrev=" >> $GITHUB_OUTPUT
         curl -s --request POST   --url https://nodle-parachain.api.onfinality.io/public   --header 'Content-Type: application/json'   --data '{
             "jsonrpc": "2.0", 
              "method": "system_version",    
              "params": [],
              "id": 1
            }' | jq '{"result"}[]' >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        id: get_version

      - name: Cache a dir
        uses: actions/cache@v3
        id: cachedir
        with:
          path: minimal
          key: ${{ get_version.eden_rev }}-snapshot

      - name: Generate Prime Numbers
        if: steps.cachedir.outputs.cache-hit != 'true'
        run: |
           install -d minimal
           date >  minimal/now
           git log > minimal/log

    - name: Use Prime Numbers
      run: |
        date
        git log
        echo CACHE::
        ls -la minimal
        cat minimal/date
        cat minimal/log
