name: Download try runtime snap

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '10 10 * * *'

env:
  try-runtime-uri: wss://api-eden.dwellir.com:443/

jobs:
  try-runtime:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Check Version
        run: |
         pwd
         touch file
         echo -n "eden_rev=" >> $GITHUB_OUTPUT
         curl -s --request POST   --url https://nodle-parachain.api.onfinality.io/public   --header 'Content-Type: application/json'   --data '{
             "jsonrpc": "2.0", 
              "method": "system_version",    
              "params": [],
              "id": 1
            }' | jq '{"result"}[]' >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        id: get_version
      - name: Run try-runtime
        uses: NodleCode/action-try-runtime/create@beta
        with:
          url: ${{ env.try-runtime-uri}}${{ secrets.DWELLIR_API_KEY}}
          snap: eden-snapshot-full

      - name: Archive snap
        uses: actions/upload-artifact@v3
        with:
          name: eden-snapshot-full
          path: eden-snapshot-full

      - name: Prepare release
        run: |
          echo '## Subwasm' > BODY
          echo '% subwasm info runtime_eden.wasm' >>BODY
          echo '% subwasm info runtime_eden.compact.wasm' >>BODY
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          generate_release_notes: true
          body_path: BODY 
          files: eden-snapshot-full