name: Download try runtime snap

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '10 10 * * *'

env:
  try-runtime-uri: wss://api-eden.dwellir.com:443/

jobs:
  try-runtime:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Check Version
        run: |
          echo -n "eden_rev=" >> $GITHUB_OUTPUT
          curl -s --request POST   --url https://nodle-parachain.api.onfinality.io/public   --header 'Content-Type: application/json'   --data '{
             "jsonrpc": "2.0", 
              "method": "system_version",    
              "params": [],
              "id": 1
            }' | jq '{"result"}[]' >> $GITHUB_OUTPUT
          export TIME=`date --iso-8601=seconds --utc`
          echo "rel_time=$TIME" >> $GITHUB_OUTPUT
          echo -n "tag=" >> $GITHUB_OUTPUT
          echo S$TIME |sed s/\+00:00//|sed s/[:-]//g >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        id: get_version
      - name: Run try-runtime
        uses: NodleCode/action-try-runtime/create@beta
        with:
          url: ${{ env.try-runtime-uri}}${{ secrets.DWELLIR_API_KEY}}
          snap: eden-snapshot-full
          options: "-p noodle-uniques"

      - name: Archive snap
        uses: actions/upload-artifact@v4.3.1
        with:
          name: eden-snapshot-full
          path: eden-snapshot-full

      - name: Prepare release
        run: |
          install -d release_doc
          echo Time: ${{ steps.get_version.outputs.rel_time }}   > release_doc/ReleaseLog
          echo Rev: ${{ steps.get_version.outputs.eden_rev }} >> release_doc/ReleaseLog
          echo Tag: ${{ steps.get_version.outputs.tag }} >> release_doc/ReleaseLog
          cat release_doc/ReleaseLog
      - name: Deploy release log branch
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release_doc/
          publish_branch: snapshot_release 
          tag_name:  ${{ steps.get_version.outputs.tag }}
          tag_message: "Automatic snapshot release"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          name: ${{ steps.get_version.outputs.tag }}
          target_commitish: snapshot_release
          tag_name: ${{ steps.get_version.outputs.tag }}
          generate_release_notes: true
          body_path: release_doc/ReleaseLog
          files: eden-snapshot-full