name: Test rust code

on:
  push:
    branches:
      - master
  pull_request:

env:
  nightly: nightly-2022-09-20
  target: wasm32-unknown-unknown
  tarpaulin-vers: "0.20.0"
  try-runtime-chain: dev
  try-runtime-uri: wss://eden-rpc.dwellir.com:443

jobs:
  try-runtime:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - name: Check Version
        run: |
         curl --request POST   --url https://nodle-parachain.api.onfinality.io/public   --header 'Content-Type: application/json'   --data '{
             "jsonrpc": "2.0", 
              "method": "system_version",    
              "params": [],
              "id": 1
            }' | jq '{"result"}[]' 

      - name: Unpack
        run: bunzip2 .maintain/paradis-snapshot-full.top.bz2; bunzip2 .maintain/paradis-snapshot-full.child.bz2

      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ env.target }}

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.nightly }}
          target: ${{ env.target }}
          default: true

      - name: Try Runtime
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --bin nodle-parachain --features=try-runtime try-runtime --execution native --chain ${{ env.try-runtime-chain }} --no-spec-name-check  on-runtime-upgrade  snap --snapshot-path=".maintain/paradis-snapshot-full"
