name: Test rust code

on:
  pull_request:
    branches:
      - master


jobs:
   download-example:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - uses: robinraju/release-downloader@v1.9
      with: 
        repository: "NodleCode/eden-snapshot"
        latest: true
        fileName: "eden-snapshot-full"
        out-file-path: "snaps"
        extract: false
    - name: Check files
      run: |
         md5sum snaps/eden-snapshot-full
         

    
