name: DevContainer

on:
  schedule:
    - cron:  '0 0 * * 0'
  pull_request:
    branches:
      - master

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World 215 Test
      uses: LeeTann/hello-world-composite-action@v1.0.0
         who-to-greet: : ${{ github.event_name != 'pull_request' }}
