name: build
on: 
  push:
    branch: master
  pull_request:
    branch: master
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - id: prep
      name: prep
      run:  { [[ ${{ github.event_name }} != pull_request ]] && echo "hello=always" || echo "hello=never" } >> $GITHUB_OUTPUT
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
